{
 "title": "Logging via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values({container_name=~\"$container_name\"}, service_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({container_name=~\"$container_name\"}, instance)"
   },
   {
    "name": "searchable_pattern",
    "label": "Search regex (case insensitive)"
   },
   { "name": "alloy_exclude", "query": "pattern_example" }
  ]
 },
 "panels": [
  { "title": "All services statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "\"$searchable_pattern\" pattern matches distribution per service",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Historical \"$searchable_pattern\" pattern matches distribution per service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[30s])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "$service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "service_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Live logs (exluded pattern of `${service_name}_exclude` variable, the same as in another pannels of service inside the raw)",
     "type": "logs",
     "description": "Live logs is a like 'tail -f' in a real time",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{container_name=~\"$container_name\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\""
      }
     ]
    },
    {
     "title": "All logs count",
     "type": "stat",
     "description": "Total  Count of log lines in the specified time range",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} !~ \"(?i)$[[service_name]]_exclude\")[$__interval]))"
      }
     ]
    },
    {
     "title": "All service logs per instance",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\"} !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "All service logs count historical change per instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\"} !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (instance)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "\"$searchable_pattern\" matches count",
     "type": "stat",
     "description": "Total Count: of $searchable_pattern in the specified time range",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval]))"
      }
     ]
    },
    {
     "title": "\"$searchable_pattern\" matches per instance",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "\"$searchable_pattern\" matches historical",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (instance)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "\"$searchable_pattern\" matches part of all logs for specified time",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) * 100 / sum(count_over_time(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} !~ \"(?i)$[[service_name]]_exclude\")[$__interval]))"
      }
     ]
    }
   ]
  }
 ]
}